### ISSUE TITLE
IOS Install issue

### ISSUE THREAD

**Issue by vietdh01** [charlesbodman/cordova-plugin-ironsource-ads#13]
Hi, I am trying to install the plugin for ios project but this error appear:

Failed to install 'cordova-plugin-ironsource-ads': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/gamezoka/Desktop/cordova/farkleking/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)

Did I miss something, I installed ironsourceSDK, please guide me, thank you very much!

**Comment by charlesbodman** [comment]
Couple questions. 

What version of cordova are you running? 

Also, try running `pod repo update` first.

**Comment by charlesbodman** [comment]
Closing due to lack of response 👍

**Comment by saqsun** [comment]
Hi,
The same issue here :(

My cordova version is:
8.1.2 (cordova-lib@8.1.1)

**Comment by charlesbodman** [comment]
@saqsun , ever get this resolved?

**Comment by saqsun** [comment]
@charlesbodman, yes submitted pull request #15 and you have merged it ;)
