### ISSUE TITLE
iOS Install Issue

### ISSUE THREAD

**Issue by DennisNicolas** [charlesbodman/cordova-plugin-ironsource-ads#22]
Hi Charles,

similar to this issue https://github.com/charlesbodman/cordova-plugin-ironsource-ads/issues/13

i see an error when trying to install the plugin for ios:

```
Installing "cordova-plugin-ironsource-ads" for ios
Failed to install 'cordova-plugin-ironsource-ads': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/path/to/project/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
(node:38516) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: pod: Command failed with exit code 1
(node:38516) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

```
Ionic:
   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.3.0
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.3.8
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.5.1

Cordova:
   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 15 other plugins)

System:
   ios-deploy : 1.9.2
   NodeJS     : v8.9.1 (/usr/local/bin/node)
   npm        : 5.5.1
   OS         : macOS Mojave
   Xcode      : Xcode 10.1 Build version 10B61
```

Thanks a lot for your work and your help!

**Comment by DennisNicolas** [comment]
After upgrading a couple of things and trying again a few days later... error is gone.

```
Ionic:

   Ionic CLI                     : 5.0.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.4.2
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.3.8
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 21 other plugins)
```
